### ISSUE TITLE
No Quit  on MacOS

### ISSUE THREAD

**Issue by s00500** [Kilian/electron-menu#2]
Hey, cool library
Is it on purpose that { role: "quit" } is not included in line 20 of index.js?
Since it is super standard to have Quit on Mac

Thanks
Lukas

**Comment by Kilian** [comment]
This got fixed in 3.0.0: https://github.com/Kilian/electron-create-menu/commit/e8466c1d366b3d6c4c4eb4f9be18a6454df2439c

See file: https://github.com/Kilian/electron-create-menu/blob/master/index.js#L20

**Comment by s00500** [comment]
Oh wow sry my bad, did only look at the old revision of the file, thank you
