### ISSUE TITLE
Electron 7: 'getName function' is deprecated and will be removed.

### ISSUE THREAD

**Issue by longsoft-dev** [Kilian/electron-menu#3]
Just wonder if you could update index.js to use app.name instead of getName()? Currently I got this message:
`(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.`

**Comment by Kilian** [comment]
Yep, it's on the todo :) Good small PR as well!

**Comment by Kilian** [comment]
fixed in 3.0.1
